name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"      # daily at 00:00 UTC
  workflow_dispatch:          # allow manual run
  push:
    branches: [ main ]        # optional

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # needed to commit the files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit snake assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake assets"
          file_pattern: assets/github-snake*.svg
